import { Prompt } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import CookieConsent from "@/components/CookieConsent"; // 👈 Add this import

const prompt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Super Jeans Furniture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${prompt.variable} ${prompt.variable} antialiased`}>
        {children}
        <Toaster />
        <CookieConsent /> {/* 👈 Mount the consent component here */}
      </body>
    </html>
  );
}
